# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestMeter3():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_meter3(self):
    self.driver.get("https://www.usms.com.bn/SmartMeter/ResLogin")
    self.driver.set_window_size(1456, 1020)
    self.driver.find_element(By.ID, "ASPxRoundPanel1_txtUsername_I").click()
    self.driver.find_element(By.ID, "ASPxRoundPanel1_txtUsername_I").send_keys("STUFF")
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(5) > td").click()
    self.driver.find_element(By.ID, "ASPxRoundPanel1_txtPassword_I").click()
    self.driver.find_element(By.ID, "ASPxRoundPanel1_txtPassword_I").send_keys("PASSSTUFF")
    self.driver.find_element(By.CSS_SELECTOR, "#ASPxRoundPanel1_btnLogin_CD > .dx-vam").click()
    self.driver.switch_to.frame(0)
    self.driver.find_element(By.CSS_SELECTOR, "#ASPxCardView1_DXCardLayout0_cell0_18_ASPxHyperLink4_0 > img").click()
    self.driver.find_element(By.ID, "cboType_I").click()
    self.driver.find_element(By.ID, "cboType_DDD_L_LBI3T0").click()
    self.driver.find_element(By.ID, "cboDateFrom_I").click()
    self.driver.find_element(By.ID, "cboDateFrom_I").click()
    self.driver.find_element(By.CSS_SELECTOR, "#UpdatePanel1 > div > table > tbody > tr:nth-child(3)").click()
    self.driver.find_element(By.ID, "cboDateFrom_I").send_keys("29-5-25")
    self.driver.find_element(By.ID, "cboDateFrom_I").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "cboDateTo_I").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(3) > td > table > tbody > tr").click()
    self.driver.find_element(By.ID, "cboDateTo_I").send_keys("29-5-25")
    self.driver.find_element(By.ID, "cboDateTo_I").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, "#btnRefresh_CD > .dx-vam").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "#btnRefresh_CD > .dx-vam")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, "#ASPxPageControl1_T1T > .dx-vam").click()
    self.driver.close()

