# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestMeter4():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_meter4(self):
    self.driver.get("https://www.usms.com.bn/SmartMeter/ResLogin")
    self.driver.set_window_size(1456, 1020)
    self.driver.find_element(By.ID, "ASPxRoundPanel1_txtUsername_I").click()
    self.driver.find_element(By.ID, "ASPxRoundPanel1_txtUsername_I").send_keys("01127182")
    self.driver.find_element(By.ID, "ASPxRoundPanel1_txtPassword_I").click()
    self.driver.find_element(By.ID, "ASPxRoundPanel1_txtPassword_I").send_keys("SmartMeter11!")
    self.driver.find_element(By.ID, "ASPxRoundPanel1_btnLogin_CD").click()
    self.driver.switch_to.frame(0)
    self.driver.find_element(By.CSS_SELECTOR, "#ASPxCardView1_DXCardLayout0_cell0_18_ASPxHyperLink4_0 > img").click()
    self.driver.find_element(By.ID, "cboType_B-1Img").click()
    self.driver.find_element(By.ID, "cboType_DDD_L_LBI3T0").click()
    self.driver.find_element(By.CSS_SELECTOR, "#btnRefresh_CD > .dx-vam").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "#btnRefresh_CD > .dx-vam")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, "#ASPxPageControl1_T1T > .dx-vam").click()
  
